version: '3.8'

services:
  inmem:
    image: redis
    networks:
      - test-xm

  xm-db:
    container_name: "xm-db"
    platform: linux/x86_64
    image: mysql:latest
    networks:
      - test-xm
    restart: always
    ports: 
      - 3306:${MYSQL_PORT}
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  xm-db2:
    container_name: "xm-db2"
    image: postgres:latest
    networks:
      - test-xm
    restart: always
    depends_on: 
      - xm-db
    ports: 
      - 5700:${POSTGRES_PORT}
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app-test-xm:
    container_name: app-test-xm
    image: app-test-xm
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - xm-db
      - xm-db2
    env_file:
      - .env
    restart: on-failure
    tty: true
    ports:
      - "7711:${PORT}"
    environment:
      ENDPOINT_URL: ${ENDPOINT_URL}
      ENV: ${ENV}
      PORT: ${PORT}
      SERVICE_NAME: ${SERVICE_NAME}
      VERSION: ${VER}

      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TIMEOUT_SEC: ${MYSQL_TIMEOUT_SEC}
      MYSQL_USER: ${MYSQL_USER}
      
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}

      REDIS_HOST: inmem
      REDIS_PORT: ${REDIS_PORT}
      REDIS_EXPIRY_SEC: ${REDIS_EXPIRY_SEC}
    networks:
      - test-xm
      
networks: 
  test-xm:
    driver: bridge

volumes:
  mysql_data:
  pgdata: