apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080
        env:
        - name: VAR_NAME_1
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: username
        - name: VAR_NAME_2
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: password
        - name: VAR_NAME_3
          valueFrom:
            configMapKeyRef:
              name: nginx-configmap
              key: host

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080