// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/sbuttigieg/test-xm/xm_app/models"
	"github.com/sbuttigieg/test-xm/xm_app/services/companies"
	"sync"
)

// Ensure, that ServiceMock does implement companies.Service.
// If this is not the case, regenerate this file with moq.
var _ companies.Service = &ServiceMock{}

// ServiceMock is a mock implementation of companies.Service.
//
// 	func TestSomethingThatUsesService(t *testing.T) {
//
// 		// make and configure a mocked companies.Service
// 		mockedService := &ServiceMock{
// 			CreateFunc: func(contextMoqParam context.Context, company *models.Company) (string, error) {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(contextMoqParam context.Context, s string) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(contextMoqParam context.Context, s string) (*models.Company, error) {
// 				panic("mock out the Get method")
// 			},
// 			UpdateFunc: func(contextMoqParam context.Context, s string, company *models.Company, strings []string) (*models.Company, error) {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedService in code that requires companies.Service
// 		// and then make assertions.
//
// 	}
type ServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(contextMoqParam context.Context, company *models.Company) (string, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(contextMoqParam context.Context, s string) error

	// GetFunc mocks the Get method.
	GetFunc func(contextMoqParam context.Context, s string) (*models.Company, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(contextMoqParam context.Context, s string, company *models.Company, strings []string) (*models.Company, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Company is the company argument value.
			Company *models.Company
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// Company is the company argument value.
			Company *models.Company
			// Strings is the strings argument value.
			Strings []string
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ServiceMock) Create(contextMoqParam context.Context, company *models.Company) (string, error) {
	if mock.CreateFunc == nil {
		panic("ServiceMock.CreateFunc: method is nil but Service.Create was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Company         *models.Company
	}{
		ContextMoqParam: contextMoqParam,
		Company:         company,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(contextMoqParam, company)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedService.CreateCalls())
func (mock *ServiceMock) CreateCalls() []struct {
	ContextMoqParam context.Context
	Company         *models.Company
} {
	var calls []struct {
		ContextMoqParam context.Context
		Company         *models.Company
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ServiceMock) Delete(contextMoqParam context.Context, s string) error {
	if mock.DeleteFunc == nil {
		panic("ServiceMock.DeleteFunc: method is nil but Service.Delete was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(contextMoqParam, s)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedService.DeleteCalls())
func (mock *ServiceMock) DeleteCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ServiceMock) Get(contextMoqParam context.Context, s string) (*models.Company, error) {
	if mock.GetFunc == nil {
		panic("ServiceMock.GetFunc: method is nil but Service.Get was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(contextMoqParam, s)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedService.GetCalls())
func (mock *ServiceMock) GetCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ServiceMock) Update(contextMoqParam context.Context, s string, company *models.Company, strings []string) (*models.Company, error) {
	if mock.UpdateFunc == nil {
		panic("ServiceMock.UpdateFunc: method is nil but Service.Update was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
		Company         *models.Company
		Strings         []string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
		Company:         company,
		Strings:         strings,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(contextMoqParam, s, company, strings)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedService.UpdateCalls())
func (mock *ServiceMock) UpdateCalls() []struct {
	ContextMoqParam context.Context
	S               string
	Company         *models.Company
	Strings         []string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
		Company         *models.Company
		Strings         []string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
